spring:
  application:
    name: utilities
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
      database: management_system
      username: root
      password: hoangsang236
      authentication-database: admin

#server:
#  port: 1234
#  host: localhost
#  ssl:
#    key-store: keystore.p12
#    key-store-password: hoangsang236
#    keyStoreType: PKCS12
#    keyAlias: tomcat

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    security: TRACE
