version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hoangsang236
      MONGO_INITDB_DATABASE: management_system
    volumes:
      - mongo_data:/data/db
      - /home/mr/JAVA/management_system_project/ultilities/database/management_system:/data/backup

volumes:
  mongo_data:
    driver: local
